import { existsSync } from "node:fs";
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { get } from "../core/config";
import { getHomeDir } from "../utils/platform";
import type { Module, ModuleContext } from "./index";

export const sshModule: Module = {
  name: "ssh",
  category: "System Preferences",
  order: 60,
  description: "Generate SSH keys and configure SSH client for GitHub",

  async run(ctx: ModuleContext): Promise<void> {
    const generateKey = get(ctx.config, "ssh.generate_key", true);
    const keyType = get(ctx.config, "ssh.key_type", "ed25519");
    let keyComment = get(ctx.config, "ssh.key_comment", "");

    // Fall back to git email for key comment
    if (!keyComment) {
      const result = await ctx.exec("git config --global user.email");
      keyComment = result.success ? result.stdout : "cider";
    }

    const home = getHomeDir();
    const sshDir = join(home, ".ssh");
    const keyPath = join(sshDir, `id_${keyType}`);
    const pubKeyPath = `${keyPath}.pub`;

    // ── Generate key ─────────────────────────────────────────────────────
    if (generateKey) {
      if (existsSync(keyPath)) {
        ctx.success(`SSH key already exists at ${keyPath}`);
      } else {
        ctx.info(`Generating ${keyType} SSH key...`);
        if (ctx.dryRun) {
          ctx.dry(`mkdir -p ${sshDir}`);
          ctx.dry(`chmod 700 ${sshDir}`);
          ctx.dry(
            `ssh-keygen -t ${keyType} -C "${keyComment}" -f ${keyPath} -N ""`,
          );
        } else {
          await mkdir(sshDir, { recursive: true });
          await chmod(sshDir, 0o700);
          const result = await ctx.exec(
            `ssh-keygen -t ${keyType} -C "${keyComment}" -f "${keyPath}" -N ""`,
          );
          if (!result.success) {
            throw new Error(`Failed to generate SSH key: ${result.stderr}`);
          }
        }
        ctx.success(`SSH key generated: ${keyPath}`);
      }
    }

    // ── SSH config ───────────────────────────────────────────────────────
    const sshConfig = join(sshDir, "config");
    if (!existsSync(sshConfig)) {
      ctx.info("Writing SSH config...");
      const configContent = `# SSH config — generated by cider

Host *
    AddKeysToAgent yes
    UseKeychain yes
    IdentityFile ${keyPath}

Host github.com
    HostName github.com
    User git
    IdentityFile ${keyPath}
    IdentitiesOnly yes
`;

      if (ctx.dryRun) {
        ctx.dry(`write ${sshConfig}`);
      } else {
        await writeFile(sshConfig, configContent);
        await chmod(sshConfig, 0o600);
      }
      ctx.success("SSH config written");
    } else {
      ctx.success("SSH config already exists (not overwriting)");
    }

    // ── Add key to macOS keychain ────────────────────────────────────────
    if (existsSync(keyPath)) {
      ctx.info("Adding SSH key to macOS keychain...");
      await ctx.exec(
        `ssh-add --apple-use-keychain "${keyPath}" 2>/dev/null || true`,
      );
    }

    // ── Copy public key to clipboard ─────────────────────────────────────
    if (existsSync(pubKeyPath) || ctx.dryRun) {
      console.log();
      ctx.info("Your public key:");
      console.log();

      if (!ctx.dryRun) {
        const pubKey = await readFile(pubKeyPath, "utf-8");
        console.log(pubKey);

        // Copy to clipboard
        const result = await ctx.exec(`cat "${pubKeyPath}" | pbcopy`);
        if (result.success) {
          ctx.success(
            "Public key copied to clipboard! Paste it at: https://github.com/settings/ssh/new",
          );
        } else {
          ctx.info("Add this key at: https://github.com/settings/ssh/new");
        }
      } else {
        ctx.dry(`cat ${pubKeyPath}`);
        ctx.dry(`pbcopy < ${pubKeyPath}`);
      }
    }
  },
};
